nep:
  environment: internet-lab
  application-name: order-tracking-app
  url: https://ncrdev-dev.apigee.net/

  services:
    override-urls:
      messaging: https://ncrdev-dev.apigee.net/order/messaging

  tech-users:
    default:
      shared-key: eef98bf4be104d97b7b8257f8b3313eb
      secret-key: b991c5188fde47c482a25545a840d454

cxf:
  logging:
    enabled: true
    mode: plain
  servlet-path: /services
  address: /rest

logging:
  level:
    root: info

spring:
  profiles:
    active: log-dev
  kafka:
    security:
      protocol: SASL_SSL
    consumer:
      bootstrap-servers: "127.0.0.1:9092"
      auto-offset-reset: latest
      username: ""
      password: ""
      group-id: "test_group"
    template:
      default-topic: "topic"

  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_tracker
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true


  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    schemas: tracked_orders

order-tracking:
  messaging:
    topic: order_tracking
    retry:
      max-retry-attempts: 3 # Maximum retry attempts before recovery
